version: '3.4'

services:
  santander.besthackernews.api:
    image: ${DOCKER_REGISTRY-}santanderbesthackernewsapi
    build:
      context: .
      dockerfile: Santander.BestHackerNews.API/Dockerfile
    ports:
     - '49205:8080'
     - '49206:8081'

  redis:
    image: redis/redis-stack-server
    restart: always
    ports:
     - '6379:6379'

  santander.besthackernews.livemanagerhost:
    image: ${DOCKER_REGISTRY-}santanderbesthackernewslivemanagerhost
    build:
      context: .
      dockerfile: Santander.BestHackerNews.LiveManagerHost/Dockerfile

